CREATE TABLE IF NOT EXISTS USERS (
  ID bigserial PRIMARY KEY,
  EMAIL varchar(256) NOT NULL UNIQUE,
  LOGIN varchar(256) NOT NULL,
  NAME varchar(256) NOT NULL,
  BIRTHDAY date NOT NULL
);

CREATE TABLE IF NOT EXISTS RELATIONS (
  FOLLOWING_USER_ID bigint,
  FOLLOWED_USER_ID bigint,
  IS_FRIENDSHIP_CONFIRMED bool,
  PRIMARY KEY (FOLLOWING_USER_ID, FOLLOWED_USER_ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
  ID bigserial PRIMARY KEY,
  NAME varchar(256) NOT NULL,
  DESCRIPTION varchar(200) NOT NULL,
  RELEASE_DATE date NOT NULL,
  DURATION int NOT NULL,
  RATING_ID int NOT NULL
);

CREATE TABLE IF NOT EXISTS LIKES (
  FILM_ID bigint,
  USER_ID bigint,
  PRIMARY KEY (FILM_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS GENRES (
  ID bigserial PRIMARY KEY,
  NAME varchar(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
  FILM_ID bigint,
  GENRE_ID bigint,
  PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS RATINGS (
  ID bigserial PRIMARY KEY,
  NAME varchar(256) NOT NULL UNIQUE
);


ALTER TABLE FILM_GENRES ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID) ON DELETE CASCADE;

ALTER TABLE FILM_GENRES ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE;

ALTER TABLE FILMS ADD FOREIGN KEY (RATING_ID) REFERENCES RATINGS (ID);

ALTER TABLE RELATIONS ADD FOREIGN KEY (FOLLOWING_USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE RELATIONS ADD FOREIGN KEY (FOLLOWED_USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE LIKES ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE LIKES ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID) ON DELETE CASCADE;
