CREATE TABLE IF NOT EXISTS USERS (
  ID bigserial PRIMARY KEY,
  EMAIL varchar,
  LOGIN varchar,
  NAME varchar,
  BIRTHDAY date
);

CREATE TABLE IF NOT EXISTS RELATIONS (
  FOLLOWING_USER_ID bigint,
  FOLLOWED_USER_ID bigint,
  IS_FRIENDSHIP_CONFIRMED bool,
  PRIMARY KEY (FOLLOWING_USER_ID, FOLLOWED_USER_ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
  ID bigserial PRIMARY KEY,
  NAME varchar,
  DESCRIPTION varchar,
  RELEASE_DATE date,
  DURATION int,
  RATING_ID int
);

CREATE TABLE IF NOT EXISTS LIKES (
  FILM_ID bigint,
  USER_ID bigint,
  PRIMARY KEY (FILM_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS GENRES (
  ID bigserial PRIMARY KEY,
  NAME varchar
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
  FILM_ID bigint,
  GENRE_ID bigint,
  PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS RATINGS (
  ID bigserial PRIMARY KEY,
  NAME varchar NOT NULL UNIQUE
);

ALTER TABLE LIKES ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID);

ALTER TABLE FILM_GENRES ADD FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID);

ALTER TABLE FILM_GENRES ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID);

ALTER TABLE FILMS ADD FOREIGN KEY (RATING_ID) REFERENCES RATINGS (ID);

ALTER TABLE RELATIONS ADD FOREIGN KEY (FOLLOWING_USER_ID) REFERENCES USERS (ID);

ALTER TABLE RELATIONS ADD FOREIGN KEY (FOLLOWED_USER_ID) REFERENCES USERS (ID);

ALTER TABLE LIKES ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);